---
title: "Genomic technologies"
# linktitle: "1. Introduction to RStudio and Images"
date: "2021-02-08"
# class_date: "2021-01-25"
output:
  blogdown::html_page:
    toc: false
menu:
  reading:
    parent: Reading
    weight: 5
type: docs
# weight: 1 
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---

## References

- Claussnitzer, Melina, Judy H. Cho, Rory Collins, Nancy J. Cox, Emmanouil T. Dermitzakis, Matthew E. Hurles, Sekar Kathiresan, et al. “[A Brief History of Human Disease Genetics](https://doi.org/10.1038/s41586-019-1879-7).” Nature, (January 2020) - Timeline and milestones in genomics development focusing on disease genetics.

- Hagen, J. B. “[The Origins of Bioinformatics](https://doi.org/10.1038/35042090).” Nature Reviews. Genetics, (01 December 2000)

- [The (near) complete sequence of a human genome](https://genomeinformatics.github.io/CHM13v1/) - efforts for completing human genome assembly

- Mardis, Elaine R. “[DNA Sequencing Technologies: 2006-2016](https://doi.org/10.1038/nprot.2016.182).” Nature Protocols, (February 2017) - DNA sequencing technologies introduction, references.

- Heather, James M., and Benjamin Chain. “[The Sequence of Sequencers: The History of Sequencing DNA](https://doi.org/10.1016/j.ygeno.2015.11.003).” Genomics, (January 2016) - Review of sequencing technologies, from pre-Sanger to current PacBio, Oxford Nanopore, Ion Torrent.

- Goodwin, Sara, John D. McPherson, and W. Richard McCombie. “[Coming of Age: Ten Years of next-Generation Sequencing Technologies](https://doi.org/10.1038/nrg.2016.49).” Nature Reviews. Genetics, (17 2016) - From microarrays to long read sequencing, single-cell sequencing. Technology review. Table with all technologies and costs. Figures.

- Green, Eric D., Mark S. Guyer, Eric D. Green, Mark S. Guyer, Teri A. Manolio, and Jane L. Peterson. “[Charting a Course for Genomic Medicine from Base Pairs to Bedside](https://doi.org/10.1038/nature09764).” Nature, (February 10, 2011) - Perspective on genomics development, technologies. Figure 1 - pictorial roadmap

- Mardis, Elaine R. “[Next-Generation DNA Sequencing Methods](https://doi.org/10.1146/annurev.genom.9.081307.164359).” Annual Review of Genomics and Human Genetics, (2008) - Sequencing technologies review. DNA-/RNA-/ChIP-seq. Figures.

- E. S. Lander et al., “[Initial Sequencing and Analysis of the Human Genome](https://doi.org/10.1038/35057062),” Nature, (February 15, 2001) - Genome sequencing landmark paper.

<!--
- Cordaux, Richard, and Mark A. Batzer. “[The Impact of Retrotransposons on Human Genome Evolution](https://doi.org/10.1038/nrg2640).” Nature Reviews. Genetics, (October 2009)

- Rothberg, Jonathan M, and John H Leamon. “The Development and Impact of 454 Sequencing.” Nature Biotechnology 26, no. 10 (October 2008): 1117–24. doi:10.1038/nbt1485. - 454 sequencing, history of sequencing development, pyrosequencing. Other technologies - Box 1, Table 2
-->

### Genomics resources

- [SequencEnG](http://education.knoweng.org/sequenceng/index.html) - An interactive learning resource for next-generation sequencing (NGS) techniques. Each technology had the corresponding reference and infographics.

- [Links and references to many resources](https://github.com/crazyhottommy/getting-started-with-genomics-tools-and-resources) by Ming Tang

- [Bioinformatics-Resources](https://github.com/YTLogos/Bioinformatics-Resources) -  A curated list of resources for learning bioinformatics.

- [biotools](https://github.com/jdidion/biotools) - A massive collection of references on the topics of bioinformatics, sequencing technologies, programming, machine learning, and more.

- [Computational genomics with R](https://compgenomr.github.io/book/) book by Altuna Akalin. [GitHub repo](https://github.com/compgenomr/book)
