---
title: "Bioconductor"
# linktitle: "1. Introduction to RStudio and Images"
date: "2021-02-22"
# class_date: "2021-01-25"
output:
  blogdown::html_page:
    toc: false
menu:
  reading:
    parent: Reading
    weight: 8
type: docs
# weight: 1 
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---

## References

- Gentleman, Robert C., Vincent J. Carey, Douglas M. Bates, Ben Bolstad, Marcel Dettling, Sandrine Dudoit, Byron Ellis, et al. “[Bioconductor: Open Software Development for Computational Biology and Bioinformatics](https://doi.org/10.1186/gb-2004-5-10-r80).” Genome Biology 5, no. 10 (2004): R80. 

- Huber, Wolfgang, Vincent J. Carey, Robert Gentleman, Simon Anders, Marc Carlson, Benilton S. Carvalho, Hector Corrada Bravo, et al. “[Orchestrating High-Throughput Genomic Analysis with Bioconductor](https://doi.org/10.1038/nmeth.3252).” Nature Methods, (February 2015) - Bioconductor overview

- Ramos, Marcel, Lucas Schiffer, Angela Re, Rimsha Azhar, Azfar Basunia, Carmen Rodriguez Cabrera, Tiffany Chan, et al. “[Software For The Integration Of Multi-Omics Experiments In Bioconductor](http://dx.doi.org/10.1158/0008-5472.can-17-0344),” June 1, 2017. - MultiAssayExperiment, Bioconductor package for management of multi-assay data

- Lawrence, Michael, Wolfgang Huber, Hervé Pagès, Patrick Aboyoun, Marc Carlson, Robert Gentleman, Martin T. Morgan, and Vincent J. Carey. “[Software for Computing and Annotating Genomic Ranges](https://doi.org/10.1371/journal.pcbi.1003118).” PLoS Computational Biology, (2013) - IRanges, GenomicRanges, GenomicFeatures packages.

### Bioconductor resources

- "[Bioconductor for Genomics Data Science](https://kasperdanielhansen.github.io/genbioconductor/)" course by Kasper Hansen. IRanges, GRanges, seqinfo, AnnotationHub, Biostrings, BSgenome, rtracklayer, and more. Includes videos, code examples and lecture material. [GitHub](https://github.com/kasperdanielhansen/genbioconductor)
 
- [Introduction to Computational Biology](https://biodatascience.github.io/compbio/) course by Mike Love. [GitHub](https://github.com/biodatascience/compbio)
 
- [Multi-omic Integration and Analysis of cBioPortal and TCGA data with MultiAssayExperiment](https://github.com/waldronlab/MultiAssayWorkshop) - workshop by Levi Waldron's group
 