---
title: "Functional enrichment analysis"
# linktitle: "1. Introduction to RStudio and Images"
date: "2021-03-22"
# class_date: "2021-01-25"
output:
  blogdown::html_page:
    toc: false
menu:
  reading:
    parent: Reading
    weight: 11
type: docs
# weight: 1 
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---

- Reimand, Jüri, Ruth Isserlin, Veronique Voisin, Mike Kucera, Christian Tannus-Lopes, Asha Rostamianfar, Lina Wadi, et al. “[Pathway Enrichment Analysis and Visualization of Omics Data Using g:Profiler, GSEA, Cytoscape and EnrichmentMap](https://doi.org/10.1038/s41596-018-0103-9).” Nature Protocols, January 21, 2019 - Pathway enrichment analysis tutorial. Main tools - g:Profiler, GSEA, Cytoscape, EnrichmentMap. Definitions, step-by-step protocol.

- Bard, Jonathan B. L., and Seung Y. Rhee. “[Ontologies in Biology: Design, Applications and Future Challenges](https://doi.org/10.1038/nrg1295).” Nature Reviews. Genetics, (March 2004) - Ontologies review

- Ackermann, Marit, and Korbinian Strimmer. “[A General Modular Framework for Gene Set Enrichment Analysis](https://doi.org/10.1186/1471-2105-10-47).” BMC Bioinformatics, (2009) - All steps for enrichment analysis, methods, statistics, GSEA.

- Efron, Bradley, and Robert Tibshirani. “[On Testing the Significance of Sets of Genes](https://doi.org/10.1214/07-AOAS101).” The Annals of Applied Statistics, 2007 - maxmean statistics for enrichment analysis. Comparison with GSEA.

- Huang, Da Wei, Brad T. Sherman, and Richard A. Lempicki. “[Bioinformatics Enrichment Tools: Paths toward the Comprehensive Functional Analysis of Large Gene Lists](https://doi.org/10.1093/nar/gkn923).” Nucleic Acids Research, (January 2009) - Gene enrichment analyses tools. Statistics, concept of background. 68 tools, table

- Hung, Jui-Hung, Tun-Hsiang Yang, Zhenjun Hu, Zhiping Weng, and Charles DeLisi. “[Gene Set Enrichment Analysis: Performance Evaluation and Usage Guidelines](https://doi.org/10.1093/bib/bbr049).” Briefings in Bioinformatics, (May 2012) - Details of GSEA. Statistics, correction for multiple testing. Lack of gold standard - concept of mutual coverage.

- Khatri, Purvesh, Marina Sirota, and Atul J. Butte. “[Ten Years of Pathway Analysis: Current Approaches and Outstanding Challenges](https://doi.org/10.1371/journal.pcbi.1002375).” PLoS Computational Biology, (2012) - Review of enrichment analyses techniques, focus on pathways, Table 1 lists tools, limitations.

- Hänzelmann, Sonja, Robert Castelo, and Justin Guinney. “[GSVA: Gene Set Variation Analysis for Microarray and RNA-Seq Data](https://doi.org/10.1186/1471-2105-14-7).” BMC Bioinformatics (January 16, 2013)  - GSVA - a GSE method that estimates variation of pathway activity over a sample population in an unsupervised manner

- Khatri, Purvesh, Marina Sirota, and Atul J. Butte. “[Ten Years of Pathway Analysis: Current Approaches and Outstanding Challenges](https://doi.org/10.1371/journal.pcbi.1002375).” PLoS Computational Biology, (February 23, 2012) - Overview of pathway analysis methods (ORA - over-representation analysis, FCS - functional class scoring, PT - pathway topology) and tools. Methods, limitations.

- Nam D., and Seon-Young K.. “[Gene-Set Approach for Expression Pattern Analysis](https://doi.org/10.1093/bib/bbn001).” Briefings in Bioinformatics 2008

- Mutation Consequences and Pathway Analysis working group. “[Pathway and Network Analysis of Cancer Genomes](https://doi.org/10.1038/nmeth.3440).” Nature Methods 2015

- de Leeuw, C. et.al. “[The Statistical Properties of Gene-Set Analysis](https://doi.org/10.1038/nrg.2016.29).” Nature Reviews 2016 
