---
title: "Epigenomics, methylation"
# linktitle: "1. Introduction to RStudio and Images"
date: "2021-04-07"
# class_date: "2021-01-25"
output:
  blogdown::html_page:
    toc: false
menu:
  reading:
    parent: Reading
    weight: 13
type: docs
# weight: 1 
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---

## Epigenomics intro

- Stephen B. Baylin and Peter A. Jones, “[A Decade of Exploring the Cancer Epigenome — Biological and Translational Implications](https://doi.org/10.1038/nrc3130),” Nature Reviews Cancer, (September 23, 2011) - Cancer epigenomics introduction, therapies

- Kagohara, Luciane T., Genevieve L. Stein-O’Brien, Dylan Kelley, Emily Flam, Heather C. Wick, Ludmila V. Danilova, Hariharan Easwaran, et al. “[Epigenetic Regulation of Gene Expression in Cancer: Techniques, Resources and Analysis](https://doi.org/10.1093/bfgp/elx018).” Briefings in Functional Genomics, August 11, 2017 - Review of epigeneitc modifications, methylation, histones, chromatin states, 3D. Technologies, databases, software. Lots of references

- Li, Bing, Michael Carey, and Jerry L. Workman. “[The Role of Chromatin during Transcription](http://www.cell.com/abstract/S0092-8674(07)00109-2).” Cell, (February 23, 2007) - Transcription process and the role of chromatin modifications. 

- Zhou, Vicky W., Alon Goren, and Bradley E. Bernstein. “[Charting Histone Modifications and the Functional Organization of Mammalian Genomes](https://www.nature.com/articles/nrg2905).” Nature Reviews. Genetics, (January 2011) - Histone marks review, ChIP-seq. Graphics of histone marks roles

- Wang, Zhibin, Dustin E. Schones, and Keji Zhao. “[Characterization of Human Epigenomes](https://doi.org/10.1016/j.gde.2009.02.001).” Current Opinion in Genetics & Development, (April 2009) - Concise description of main histone marks, their roles in transcription, and the corresponding studies. Figure 2 - schematic distribution of histone marks with respect to genes-TSSs.

- Zhang, Z. D., A. Paccanaro, Y. Fu, S. Weissman, Z. Weng, J. Chang, M. Snyder, and M. B. Gerstein. “[Statistical Analysis of the Genomic Distribution and Correlation of Regulatory Elements in the ENCODE Regions](https://doi.org/10.1101/gr.5573107).” Genome Research, (June 1, 2007) - ENCODE pilot project analysis. Non-random location of regulatory elements. Enrichment in TSSs, not in the middle or end of transcription sites. PCA and biplot representation of interrelatedness among TFs and histone marks, clustering.

- Huen, David S., and Steven Russell. “[On the Use of Resampling Tests for Evaluating Statistical Significance of Binding-Site Co-Occurrence](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-11-359).” BMC Bioinformatics (June 30, 2010) - Thorough review on permutation. Problem with different numbers of ROIs/epiregions in permutations. Regions may overlap (i.e., occur in clusters). Independent assignment is best.

## Epigenomic enrichment

- McLean, Cory Y., Dave Bristor, Michael Hiller, Shoa L. Clarke, Bruce T. Schaar, Craig B. Lowe, Aaron M. Wenger, and Gill Bejerano. “[GREAT Improves Functional Interpretation of Cis-Regulatory Regions](https://doi.org/10.1038/nbt.1630).” Nature Biotechnology 28, no. 5 (May 2010) - Hypergeometric and binomial enrichment of regulatory regions in relation to genesgenomic regions and their ontologies.

- De, Subhajyoti, Brent S. Pedersen, and Katerina Kechris. “[The Dilemma of Choosing the Ideal Permutation Strategy While Estimating Statistical Significance of Genome-Wide Enrichment](https://doi.org/10.1093/bib/bbt053).” Briefings in Bioinformatics 15, no. 6 (November 2014)

- Dozmorov, Mikhail G. “[Epigenomic Annotation-Based Interpretation of Genomic Data: From Enrichment Analysis to Machine Learning](https://doi.org/10.1093/bioinformatics/btx414).” Bioinformatics (Oxford, England) 33, no. 20 (October 15, 2017)

### Hidden Markov Models, genome segmentation overview

- Eddy, Sean R. “[What Is a Hidden Markov Model?](https://doi.org/10.1038/nbt1004-1315)” Nature Biotechnology, (October 2004)

- Eddy, S. R. “[Multiple Alignment Using Hidden Markov Models](https://pdfs.semanticscholar.org/bc1e/ffe17026c1396697e4ea2b399f7a049202fc.pdf).” Proceedings. International Conference on Intelligent Systems for Molecular Biology (1995) - HMMER hidden markov models for protein sequence alignment. First paper

- Schuster-Böckler, Benjamin, and Alex Bateman. “[An Introduction to Hidden Markov Models](https://doi.org/10.1002/0471250953.bia03as18).” 2007 - Hidden Markov Models primer

- L.R. Rabiner, “[A Tutorial on Hidden Markov Models and Selected Applications in Speech Recognition](https://doi.org/10.1109/5.18626),” Proceedings of the IEEE, (February 1989) - Theory and statistics of Hidden Markov Models. Very detailed, thorough

- Ernst, Jason, and Manolis Kellis. “[Chromatin-State Discovery and Genome Annotation with ChromHMM](https://doi.org/10.1038/nprot.2017.124).” Nature Protocols, (December 2017) - ChromHMM protocol. Intro about ChromHMM, other methods. Links to genome annotation models.

- Hoffman, Michael M., Orion J. Buske, Jie Wang, Zhiping Weng, Jeff A. Bilmes, and William Stafford Noble. “[Unsupervised Pattern Discovery in Human Chromatin Structure through Genomic Segmentation](https://doi.org/10.1038/nmeth.1937).” Nature Methods 9, no. 5 (May 2012) - Segway - segmentation and prediction of genomic states. Using dynamic Bayesian network

### Methylation 

- Pidsley, R., et. al., and Susan J. Clark. "[Critical Evaluation of the Illumina MethylationEPIC BeadChip Microarray for Whole-Genome DNA Methylation Profiling](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-1066-1)." Genome Biology 2016

- Pan D., et. al. "[Comparison of Beta-value and M-value methods for quantifying methylation levels by microarray analysis](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-11-587)." BMC Bioinformatics, 2010

- Bock, Christoph, Eleni M Tomazou, Arie B Brinkman, Fabian Müller, Femke Simmer, Hongcang Gu, Natalie Jäger, Andreas Gnirke, Hendrik G Stunnenberg, and Alexander Meissner. “[Quantitative Comparison of Genome-Wide DNA Methylation Mapping Technologies](https://doi.org/10.1038/nbt.1681).” Nature Biotechnology, (October 2010) - Methylation intro, technology. Software tools, tables. Quality control and problems. Differential analysis. Public repositories.

- Krueger, Felix, Benjamin Kreck, Andre Franke, and Simon R Andrews. “[DNA Methylome Analysis Using Short Bisulfite Sequencing Data](https://www.nature.com/articles/nmeth.1828).” Nature Methods, (January 30, 2012) - Methylation intro, technologies to measure. Alignment problems, QC considerations, processing workflow. Theoretical, references.

- Wreczycka, Katarzyna, Alexander Gosdschan, Dilmurat Yusuf, Bjoern Gruening, Yassen Assenov, and Altuna Akalin. “[Strategies for Analyzing Bisulfite Sequencing Data](https://www.sciencedirect.com/science/article/pii/S0168165617315936),” August 9, 2017 - Bisufite sequencing data analysis steps. Intro into methylation. Refs to packages. 

- Robinson, Mark D., Abdullah Kahraman, Charity W. Law, Helen Lindsay, Malgorzata Nowicka, Lukas M. Weber, and Xiaobei Zhou. “[Statistical Methods for Detecting Differentially Methylated Loci and Regions](https://doi.org/10.3389/fgene.2014.00324).” Frontiers in Genetics (2014) - Methylation review, technology, databases, experimental design, statistics and tools for differential methylation detection, beta-binomial distribution, cell type deconvolution.

- Krueger, Felix, and Simon R. Andrews. “[Bismark: A Flexible Aligner and Methylation Caller for Bisulfite-Seq Applications](https://doi.org/10.1093/bioinformatics/btr167).” Bioinformatics, (June 1, 2011) - Bismark paper. stranded and unstranded BS sequencing. Conversion of reads, genomes, best alignment strategy. https://www.bioinformatics.babraham.ac.uk/projects/bismark/

- Xi, Yuanxin, and Wei Li. “[BSMAP: Whole Genome Bisulfite Sequence MAPping Program](https://doi.org/10.1186/1471-2105-10-232).” BMC Bioinformatics, (2009) - BSMAP paper. Bisulphite conversion technology introduction, problems. BSMAP algorithm. Very good figures explaining all steps. [BSMAP software](https://code.google.com/archive/p/bsmap/)

- Chen, Yunshun, Bhupinder Pal, Jane E. Visvader, and Gordon K. Smyth. “[Differential Methylation Analysis of Reduced Representation Bisulfite Sequencing Experiments Using EdgeR](https://doi.org/10.12688/f1000research.13196.1).” F1000Research (November 28, 2017) - RRBS differential methylation analysis. Methylation intro. R code tutorial. 

- Teschendorff, Andrew E., and Caroline L. Relton. “[Statistical and Integrative System-Level Analysis of DNA Methylation Data](https://doi.org/10.1038/nrg.2017.86).” Nature Reviews Genetics, November 13, 2017 - Deconvolution of methylation profiles. Reference-based, reference-free, semi-reference-free. Table 1 - tools

- Methylation statistics packages: Table 2 in Liu, Hongbo, Song Li, Xinyu Wang, Jiang Zhu, Yanjun Wei, Yihan Wang, Yanhua Wen, et al. “[DNA Methylation Dynamics: Identification and Functional Annotation](https://www.ncbi.nlm.nih.gov/pubmed/27515490).” Briefings in Functional Genomics, 2016

- Mark D. Robinson et al., “[Statistical Methods for Detecting Differentially Methylated Loci and Regions](https://doi.org/10.3389/fgene.2014.00324),” Frontiers in Genetics 5 (2014) - Methylation nethods review. From data, experimental design to software tools for finding differentially methylated regions.

- Shafi, Adib, Cristina Mitrea, Tin Nguyen, and Sorin Draghici. “[A Survey of the Approaches for Identifying Differential Methylation Using Bisulfite Sequencing Data](https://doi.org/10.1093/bib/bbx013).” Briefings in Bioinformatics, March 8, 2017 - Review of differential methylation methods and 22 tools. Categorized by approaches. [Pros and cons of each approach](https://academic.oup.com/view-large/figure/121909042/bbx013f3.tif), [Table 1. Summary of the important characteristics of the 22 surveyed approaches](https://academic.oup.com/view-large/121909044), [Table 2. Comparison of the available implementations of the 22 surveyed approaches](https://academic.oup.com/view-large/121909057)

- Wreczycka, Katarzyna, Alexander Gosdschan, Dilmurat Yusuf, Björn Grüning, Yassen Assenov, and Altuna Akalin. “[Strategies for Analyzing Bisulfite Sequencing Data](https://doi.org/10.1016/j.jbiotec.2017.08.007).” Journal of Biotechnology (November 2017) - Review of bisulfite sequencing technology, data preprocessing, and analysis methods and tools. Differential methylation.

- Venet, D., F. Pecasse, C. Maenhaut, and H. Bersini. “[Separation of Samples into Their Constituents Using Gene Expression Data](https://academic.oup.com/bioinformatics/article/17/suppl_1/S279/262438).” Bioinformatics (2001) - Statistical derivation of deconvolution. 

