---
title: General References
menu:
  reading:
#    parent: Reading details
    weight: 1
type: docs
weight: 1
---

Topic-specific references will be posted here. Class-specific reading assignments will be posted under the [Assignments](/assignment/) section following each class.


### Acknowledgements

This course would be impossible without many resources and material shared by others, listed at [Bioinformatics notes](https://github.com/mdozmorov/Bioinformatics_notes) GitHub repository.

- [Applied Computational Genomics](https://github.com/quinlan-lab/applied-computational-genomics) course, by Aaron Quinlan, links to slides, [Youtube playlist](https://www.youtube.com/playlist?list=PLCbXw1opqIQeNfF26-wWegdGoCC1aut0P) with full lecture videos

- [Foundations of Computational and Systems Biology](https://ocw.mit.edu/courses/biology/7-91j-foundations-of-computational-and-systems-biology-spring-2014/index.htm) MIT course, by Christopher Burge, David Gifford, Ernest Fraenkel, slides, [Youtube playlist](https://www.youtube.com/playlist?list=PLUl4u3cNGP63uK-oWiLgO7LLJV6ZCWXac)

- [Introduction to Computational Biology](https://biodatascience.github.io/compbio/) course by Michael Love, course material, [GitHub](https://github.com/biodatascience/compbio) 

- [STAT115/215 BST/BIO282](https://github.com/liulab-dfci/bioinfo-combio) course by Xiaole Shirley Liu, [Bookdown](https://liulab-dfci.github.io/bioinfo-combio/), [Youtube playlist](https://www.youtube.com/playlist?list=PLeB-Dlq-v6tY3QLdQBA7rwb4a7fK9mLpv)

- [Biomedical Data Science PH525x](https://genomicsclass.github.io/book/) course by Rafael Irizarry and Michael Love, course material, [GitHub](https://github.com/genomicsclass/labs)

- [Algorithms for DNA Sequencing](https://github.com/BenLangmead/ads1-slides) course by Ben Langmead, slies, [Youtube playlist](https://www.youtube.com/playlist?list=PL2mpR0RYFQsBiCWVJSvVAO3OJ2t7DzoHA) with short videos. [More teaching material](http://www.langmead-lab.org/teaching-materials/)

<!-- **Introduction to Computational Biology** course, by Steven Skiena. [Course web site](https://www3.cs.stonybrook.edu/~skiena/549/) with course material, [Youtube playlist](https://www.youtube.com/watch?v=pJAIalWDgY0&list=PLA48145CC64FE7990) with full lecture videos -->

- [Bioconductor for Genomic Data Science](https://kasperdanielhansen.github.io/genbioconductor/) course by Kasper Hansen, short videos, slides, code

- [Picking Up The Tabb](https://pickingupthetabb.wordpress.com/building-a-bioinformaticist/free-online-training-in-bioinformatics-and-biostatistics/) video course by David Tabb, slides

- [Applied Genomics](https://github.com/schatzlab/appliedgenomics2018) course by Michael Schatz, lectures and assignments. [More teaching material](http://schatzlab.cshl.edu/teaching/)

- [Bioinformatics Coffee Hour](https://github.com/harvardinformatics/bioinformatics-coffee-hour) - Short lessons from FAS Informatics coffee hour, Harvard

<!--- [Course material by David Tabb](https://pickingupthetabb.wordpress.com/building-a-bioinformaticist/free-online-training-in-bioinformatics-and-biostatistics/), full lecture videos and slides

[Course material by Ingo Ruczinski, JHU](http://www.biostat.jhsph.edu/~iruczins/teaching/) -->

