---
title: "Genomic resources"
# linktitle: "1. Introduction to RStudio and Images"
date: "2021-02-10"
class_date: "2021-02-10"
output:
  blogdown::html_page:
    toc: false
menu:
  class:
    parent: Class sessions
    weight: 5
type: docs
# weight: 1 
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---

## Slides

### File formats

<a href="../../slides/03_Genomic_resources/01_File_formats.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/03_Genomic_resources/01_File_formats.html#1')
```

### Genomic Resources

<a href="../../slides/03_Genomic_resources/02_Genomic_Resources.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/03_Genomic_resources/02_Genomic_Resources.html#1')
```

### The Cancer Genome Atlas (TCGA)

<a href="../../slides/03_Genomic_resources/03_TCGA.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/03_Genomic_resources/03_TCGA.html#1')
```
