---
title: "Clustering"
# linktitle: "1. Introduction to RStudio and Images"
date: "2021-03-29"
class_date: "2021-03-26"
output:
  blogdown::html_page:
    toc: false
menu:
  class:
    parent: Class sessions
    weight: 11
type: docs
# weight: 1 
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---

## Slides

### Hierarchial clustering

<a href="../../slides/09_Clustering/Clustering.html" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/09_Clustering/Clustering.html')
```

<a href="../../slides/09_Clustering/lab/Average_linkage.R" target="_blank">Average_linkage.R</a>, <a href="../../slides/09_Clustering/lab/Single_Linkage.R" target="_blank">Single_Linkage.R</a>, <a href="../../slides/09_Clustering/lab/Complete_Linkage.R" target="_blank">Complete_Linkage.R</a>, <a href="../../slides/09_Clustering/lab/Divisive_Kmeans.R" target="_blank">Divisive_Kmeans.R</a>, <a href="../../slides/09_Clustering/lab/CramersV_gower.R" target="_blank">CramersV_gower.R</a>

### Dimensionality reduction

<a href="../../slides/09_Clustering/Clustering1.html" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/09_Clustering/Clustering1.html')
```

<a href="../../slides/09_Clustering/lab/Kmeans_PAM.R" target="_blank">Kmeans_PAM.R</a> (<a href="../../slides/09_Clustering/data/BreastCancer.RData" target="_blank">Data</a>), <a href="../../slides/09_Clustering/lab/PCA.R" target="_blank">PCA.R</a> (<a href="../../slides/09_Clustering/data/nci60.tsv" target="_blank">Data</a>), <a href="../../slides/09_Clustering/lab/MDS.Rmd" target="_blank">MDS.Rmd</a>

### Clustering QC

<a href="../../slides/09_Clustering/Clustering2.html" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/09_Clustering/Clustering2.html')
```

