---
title: "Final project"
# linktitle: "1. Introduction to RStudio and Images"
date: "2021-05-03"
due_date: "2021-05-03"
due_time: "5:00 AM"
output:
  blogdown::html_page:
    toc: false
menu:
  class:
    parent: Class sessions
    weight: 99
type: docs
# weight: 1 
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---


**General description**: The purpose of the final project is for you to gain familiarity with the main methods learned in class, applied to experimental sequencing data. Additionally, the project should help solidify your statistical and practical understanding of such methods.

<!--For your project, you are required to complete two parts - 1) processing and analysis of raw RNA-seq data and 2) performing integrative analysis of two types of processed TCGA data, e.g., gene expression and methylation, or gene expression and ATAC-seq.-->

## Processing and analysis of RNA-seq data

### Dataset selection (due April 12, 2021, 5:00pm EDT)

You must select an RNA-seq dataset to analyze. Prerequisites for a dataset: 

- at least two experimental conditions.
- at least three samples per condition.
- human data, but model organism data are acceptable.
- cancer-specific data is preferred, but other diseases are acceptable.
- mRNA (gene expression) is preferred, but different data types (e.g., methylation) may be acceptable after discussion with the instructor.
<!--- your own data permitted after discussion with the instructor.-->

<!--Choose experimental condition of interest (e.g., a particular cancer type, environmental exposure, immunologic or neurologic disease). -->Search the [NCBI Gene Expression Omnibus (GEO) database](http://www.ncbi.nlm.nih.gov/geo/), using keywords of interest, e.g., "prostate cancer RNA-seq." 

Find and read the associated paper describing the dataset - it should report differentially expressed genes and functional enrichment analysis results. Aim to re-create the published results. Submit the description of the data ("Introduction/Background" section, see "Reporting requirements" section).

### Analysis (due May 3, 2021, 5:00pm EDT)

Perform the following analyses, explain your observations in each.

- Download raw FASTQ files, describe the process.
- Perform data quality control using `FASTQC` followed by `multiqc`.
- Perform adapter trimming using `Trimgalore` and `Trimmomatic`.
- Align the data using `bowtie2` and `STAR` aligners.
- Obtain gene counts using `featureCounts` and `HTSeq-count`.
- Exploratory data analysis: Number of samples per condition, gene expression distribution per sample (boxplots), correlogram (`ComplexHeatmap`), PCA.
- Differential expression analysis using `edgeR` and `DESeq2`. Make the heatmap (`ComplexHeatmap`) and the volcano plot (`EnhancedVolcano`) of differentially expressed genes.
- Perform functional enrichment analysis (hypergeometric test and GSEA) of differentially expressed genes using Gene Ontology, KEGG, and MSigDb (`clusterProfiler`). Visualize two top KEGG pathways (`pathviewer`) and overlay differentially expressed genes.
- Compare lists of differentially expressed genes obtained after two different pipelines and the functional enrichment analysis results. Use a Venn diagram (`VennDetail`) and consider the up- and downregulated directionality of changes. Describe the discrepancies. 
- Compare lists of differentially expressed genes obtained after two different pipelines and the functional enrichment analysis results with those reported in the original paper. Describe the discrepancies.

**Teamwork:** One team will use the same dataset. One team member will use one sequence of tools (e.g., Trimgalore-bowtie2-featureCounts), nonoverlapping with tools used by another. Both team members should explore and understand the functionality of all tools. Each team member will submit their own report. If working individually, use one sequence of tools only and perform a comparison with published results.


<!--
## 2. Integrative analysis of two types of processed TCGA data

Use Breast Cancer (BRCA) TCGA data. Select two data types, one should be RNA-seq and another may be ATAC-seq, DNA methylation, or other. Note that the additional data type should be considered in the context of genes, e.g., ATAC-seq peaks should be mapped to the nearby genes. Explore [GDC TCGA Breast Cancer (BRCA)](https://xenabrowser.net/datapages/?cohort=GDC%20TCGA%20Breast%20Cancer%20(BRCA)&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443) or [curatedTCGAData](	https://bioconductor.org/packages/curatedTCGAData/) data access options.

Perform the following analyses, explain your observations in each.

- Perform exploratory data analysis on gene expression - number of samples (total, and in each PAM50 subtype), number of genes, gene expression type (counts, RPKM/FPKM, TPM) and scale (raw or $log_2$), was the data normalized. Make a PCA plot (and/or, MDS, tSNE plots) colored by PAM50 subtypes.
    - Repeat for another data type.
- Select samples for two breast cancer subtypes from the "PAM50Call_RNAseq" annotation, e.g., "Basal" and "LumA." Perform differential expression analysis between the two conditions using `edgeR` and `DESeq2`. Compare the results, explain the discrepancies.
    - Repeat for another data type.
- Plot gene expression (X-axis) vs. another data type (Y-axis) levels for the differentially expressed genes. Select groups of genes with concordant changes, i.e., upregulated genes with decreased methylation level.
- Perform functional enrichment analysis of concordant and discordant groups of differentially expressed genes.
-->


# Reporting requirements

Your project reports should be written in R/Markdown format and compiled as a PDF document. Follow [the IMRaD format](https://writingcenter.gmu.edu/guides/writing-an-imrad-report) when describing your project and results. Be concise when describing the results. Embed figures, small tables, and references in the report. Make supplementary figures/tables for large results output, if needed. For each part, address the following points:

- A simple and clear description of the datasets and the research question you are addressing. This should be written in the form of an **Introduction/Background** section(s).
-  A **Methods** section
-  A **Results** section providing a description of your results. Tables and figures should be numbered and captioned.
    - **Data component:** Include description/code for obtaining and processing raw data; do not include raw data files. Include processed data/results as text or CSV files that your code chunks will process/generate. Gzip text files.
    - **Computational component**: code chunks analyzing the data in the Rmd file. Make sure your code is readable (use `formatR::tidy_app()` or the `styler` R packages), and commented.
- A **Discussion/Conclusion** section. 
- **References**.

# Submitting guidelines

- Submit Rmds and PDFs of the reports to the blackboard, https://blackboard.vcu.edu
- Include a compressed project folder with your code, processed data/results in text/CSV format. Do not include raw data; instead, provide description/code for data downloading. The total size of the submission should not exceed 10Mb.

# Due date

**May 3, 2021, at 5:00pm EDT.**